import { Product, Category, Seller, HelpArticle, Order } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Electronics', slug: 'electronics', iconName: 'Laptop', count: 1450 },
  { id: '2', name: 'Mobiles', slug: 'mobiles', iconName: 'Laptop', count: 820 },
  { id: '3', name: 'Laptops', slug: 'laptops', iconName: 'Laptop', count: 420 },
  { id: '4', name: 'Fashion', slug: 'fashion', iconName: 'Shirt', count: 1890 },
  { id: '5', name: 'Footwear', slug: 'footwear', iconName: 'Shirt', count: 650 },
  { id: '6', name: 'Beauty', slug: 'beauty', iconName: 'Sparkles', count: 710 },
  { id: '7', name: 'Grocery', slug: 'grocery', iconName: 'Home', count: 540 },
  { id: '8', name: 'Home & Kitchen', slug: 'home-kitchen', iconName: 'Home', count: 820 },
  { id: '9', name: 'Furniture', slug: 'furniture', iconName: 'Home', count: 310 },
  { id: '10', name: 'Sports', slug: 'sports', iconName: 'Activity', count: 460 },
  { id: '11', name: 'Toys', slug: 'toys', iconName: 'Activity', count: 380 },
  { id: '12', name: 'Books', slug: 'books', iconName: 'BookOpen', count: 420 },
  { id: '13', name: 'Automotive', slug: 'automotive', iconName: 'Laptop', count: 290 },
  { id: '14', name: 'Health', slug: 'health', iconName: 'Activity', count: 510 },
  { id: '15', name: 'Watches', slug: 'watches', iconName: 'Laptop', count: 680 },
  { id: '16', name: 'Jewelry', slug: 'jewelry', iconName: 'Sparkles', count: 490 },
  { id: '17', name: 'Baby Products', slug: 'baby-products', iconName: 'Sparkles', count: 350 },
  { id: '18', name: 'Smart Home', slug: 'smart-home', iconName: 'Home', count: 420 }
];

export const sellers: Seller[] = [
  {
    id: 'v1',
    name: 'AuraTech Officials',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 3120,
    joinedDate: 'Jan 2024',
    productsCount: 42,
    balance: 4890.50,
    totalSales: 165400.00,
    commissionRate: 0.08,
    isApproved: true,
    status: 'active',
    email: 'contact@auratech.io'
  },
  {
    id: 'v2',
    name: 'Vogue Essentials',
    logo: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=150&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 1450,
    joinedDate: 'Mar 2024',
    productsCount: 88,
    balance: 2310.20,
    totalSales: 78200.00,
    commissionRate: 0.12,
    isApproved: true,
    status: 'active',
    email: 'info@vogueessentials.com'
  },
  {
    id: 'v3',
    name: 'EcoVentures',
    logo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 890,
    joinedDate: 'Jun 2024',
    productsCount: 15,
    balance: 1450.00,
    totalSales: 34100.00,
    commissionRate: 0.10,
    isApproved: true,
    status: 'active',
    email: 'support@ecoventures.com'
  },
  {
    id: 'v4',
    name: 'Apex Athletics',
    logo: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=150&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 620,
    joinedDate: 'Aug 2024',
    productsCount: 29,
    balance: 890.00,
    totalSales: 21600.00,
    commissionRate: 0.10,
    isApproved: false,
    status: 'pending',
    email: 'onboarding@apexathletics.net'
  }
];

export const products: Product[] = [
  // SECTION: ELECTRONICS
  {
    id: 'p1',
    title: 'SoundAura Wireless ANC Headphones',
    price: 4999,
    originalPrice: 6999,
    description: 'Experience professional-grade audiophile sound. Features standard hybrid active noise cancellation (ANC), 45-hour quick-charge battery life, and spatial audio matching with smart voice controls.',
    category: 'electronics',
    rating: 4.8,
    ratingCount: 124,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    specs: { 'Battery': '45 Hours', 'Noise Cancelling': 'Yes (Hybrid ANC)', 'Bluetooth': 'v5.3', 'Warranty': '2 Years' },
    stock: 18,
    featured: true
  },
  {
    id: 'p-elec-2',
    title: 'NexaView 4K Ultra HD Smart LED TV (55 inch)',
    price: 38999,
    originalPrice: 49999,
    description: 'Step into spectacular clarity. Powered by Nexa Neural Cinema Processor, standard HDR10 Pro support, and immersive 30W Dolby Atmos front speakers.',
    category: 'electronics',
    rating: 4.7,
    ratingCount: 89,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600&auto=format&fit=crop&q=80',
    specs: { 'Display size': '55 inches', 'Resolution': '4K UHD (3840x2160)', 'Smart Platform': 'Nexa OS (WebOS)', 'Refresh Rate': '60 Hz' },
    stock: 12
  },
  {
    id: 'p-elec-3',
    title: 'AuraBoom Waterproof Portable Bluetooth Speaker',
    price: 2499,
    originalPrice: 3999,
    description: 'Engineered for extreme environments. Massive 24W peak dual output with deep passive subwoofers, IPX7 swimming-pool safe body, and 20-hour wireless playtime.',
    category: 'electronics',
    rating: 4.5,
    ratingCount: 76,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80',
    specs: { 'Output power': '24W Stereo', 'Water Resistance': 'IPX7 Waterproof', 'Battery Life': '20 Hours', 'Weight': '540g' },
    stock: 24
  },
  {
    id: 'p-elec-4',
    title: 'NexaCharge 20000mAh Dual Port Power Bank',
    price: 1499,
    originalPrice: 2499,
    description: 'Ultra-high density battery bank backing you on long flights. Supports standard Power Delivery (PD 22.5W) fast recharge, dual smart USB output, and LED power reserve scale.',
    category: 'electronics',
    rating: 4.6,
    ratingCount: 145,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
    specs: { 'Capacity': '20000 mAh', 'Fast Charge Port': 'USB-C PD 22.5W', 'Recharge Time': '4.5 Hours', 'Protection': '12-Layer Safety Shield' },
    stock: 45
  },
  {
    id: 'p8',
    title: 'GridTech Ergonomic Wireless Keyboard & Mouse Combo',
    price: 1899,
    originalPrice: 2999,
    description: 'Aesthetic and silent workspace upgrade. Low profile scissor keys coupled with an optical precision silent click mouse. Multi-device connect with simple key toggles.',
    category: 'electronics',
    rating: 4.4,
    ratingCount: 53,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    specs: { 'Wireless Tech': '2.4GHz & Bluetooth', 'Key Mechanism': 'Silent Scissor Switch', 'Mouse DPI': '1600 DPI (3-level adjustment)', 'Battery': 'Rechargeable Type-C' },
    stock: 15
  },

  // SECTION: MOBILES
  {
    id: 'p-mob-1',
    title: 'NexaPro 5G Speedster Android Smartphone',
    price: 18999,
    originalPrice: 24999,
    description: 'Blazing performance with native 5G. Features Octa-core Dimensity processing chip, stunning 6.5 inch 120Hz Super AMOLED display, and 50MP triple-lens visual array.',
    category: 'mobiles',
    rating: 4.5,
    ratingCount: 112,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    specs: { 'Processor': 'MediaTek Dimensity 7050', 'RAM/Storage': '8GB / 128GB', 'Camera': '50MP + 8MP + 2MP', 'Battery': '5000 mAh (33W Fast)' },
    stock: 25,
    featured: true
  },
  {
    id: 'p-mob-2',
    title: 'Aura Lite Efficient Budget Smartphone',
    price: 8499,
    originalPrice: 11999,
    description: 'Standard smartphone engineered for daily reliability. Clean near-stock Android OS, standard 6.5 inch screen, day-and-night battery, and triple card slots.',
    category: 'mobiles',
    rating: 4.2,
    ratingCount: 64,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&q=80',
    specs: { 'RAM/Storage': '4GB / 64GB', 'Battery': '5000 mAh', 'Processor': 'Unisoc T612', 'Camera': '13MP Dual AI' },
    stock: 35
  },
  {
    id: 'p-mob-3',
    title: 'Nexa Prime Titanium 5G Smartphone',
    price: 54999,
    originalPrice: 64999,
    description: 'Superb craftsmanship. Grade 5 aircraft-grade Titanium body, native 200MP cinematic lens, high definition dynamic island OLED, and Snapdragon 8 Gen-3 engine.',
    category: 'mobiles',
    rating: 4.9,
    ratingCount: 205,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    specs: { 'Casing': 'Grade 5 Titanium', 'RAM/Storage': '12GB / 256GB', 'Processor': 'Snapdragon 8 Gen 3', 'Camera': '200MP + 50MP + 12MP' },
    stock: 15
  },
  {
    id: 'p-mob-4',
    title: 'Glitch 120Hz Ultra Gaming Smartphone',
    price: 28999,
    originalPrice: 35999,
    description: 'Unleash peak framerates. Integrated liquid copper vapour cooling, high sensitivity 360Hz touch sampling rate on custom HDR15 panel, and quick bypass charging direct-to-motherboard.',
    category: 'mobiles',
    rating: 4.7,
    ratingCount: 92,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    specs: { 'Processor': 'Snapdragon 8s Gen 3', 'RAM/Storage': '12GB / 256GB', 'Screen': '6.78" 144Hz AMOLED', 'Cooling': 'ICE 11.0 Liquid Cooling' },
    stock: 19
  },
  {
    id: 'p-mob-5',
    title: 'TurboCharge 65W Multi Charger & Cable Kit',
    price: 1199,
    originalPrice: 1999,
    description: 'Sleek GaN compact desktop charger. Triple charge output matching smartphones, laptops, and tablets seamlessly. Comes bundled with armored e-marked smart cable.',
    category: 'mobiles',
    rating: 4.6,
    ratingCount: 51,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
    specs: { 'Wattage': '65W Max GaN', 'Ports': '2x USB-C + 1x USB-A', 'Cable': '1.5m 100W Armored C-to-C', 'Certifications': 'BIS Safety Certified' },
    stock: 40
  },

  // SECTION: LAPTOPS
  {
    id: 'p-lap-1',
    title: 'NexaBook Thin & Light Student Laptop',
    price: 32999,
    originalPrice: 42999,
    description: 'Highly portable companion ideal for coursework. Features standard Intel Core i3 processor, fast SSD architecture, and clean aluminum lid. All-day standby battery backup.',
    category: 'laptops',
    rating: 4.3,
    ratingCount: 88,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1496181130204-7552cc1524e2?w=600&auto=format&fit=crop&q=80',
    specs: { 'Processor': 'Intel Core i3 12th Gen', 'RAM/Storage': '8GB DDR4 / 512GB SSD', 'Display': '15.6" Full HD Anti-glare', 'Weight': '1.65 kg' },
    stock: 14,
    featured: true
  },
  {
    id: 'p-lap-2',
    title: 'Pyre GTX Core i7 Gaming Laptop',
    price: 74999,
    originalPrice: 94999,
    description: 'Dominate esports lobbies. Superb Intel Core i7 processor matched with NVIDIA RTX graphics. 144Hz IPS display frame fluidness for high-stakes competition.',
    category: 'laptops',
    rating: 4.7,
    ratingCount: 65,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&auto=format&fit=crop&q=80',
    specs: { 'Processor': 'Intel Core i7 13th Gen', 'GPU': 'NVIDIA RTX 4050 (6GB)', 'RAM/Storage': '16GB DDR5 / 1TB SSD', 'Screen': '15.6" IPS 144Hz' },
    stock: 9
  },
  {
    id: 'p-lap-3',
    title: 'NexaWork Premium Steel Business Laptop',
    price: 48999,
    originalPrice: 59999,
    description: 'Productivity workhorse. Carbon composite chassis, ergonomic spill-resistant backlit keybed, integrated biometric visual recognition, and rapid express recharge.',
    category: 'laptops',
    rating: 4.6,
    ratingCount: 42,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1541857182-012a9756b16d?w=600&auto=format&fit=crop&q=80',
    specs: { 'Processor': 'AMD Ryzen 5 7530U', 'RAM/Storage': '16GB DDR4 / 512GB NVMe', 'OS': 'Windows 11 Home & Office', 'Battery Life': '12 Hours' },
    stock: 12
  },
  {
    id: 'p-lap-4',
    title: 'AuraArt Pro 4K Creator Laptop',
    price: 85999,
    originalPrice: 105000,
    description: 'Stunning colors for creative designers. Calibrated UHD OLED screen presenting standard 100% DCI-P3 color profiles, multi precision haptic tracks, and massive cooling channels.',
    category: 'laptops',
    rating: 4.8,
    ratingCount: 38,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&auto=format&fit=crop&q=80',
    specs: { 'Display': '16" 4K OLED HDR', 'Color Accuracy': 'Delta E < 1', 'Processor': 'Intel Core i9 13th Gen', 'Memory': '32GB DDR5 / 1TB NVMe' },
    stock: 6
  },
  {
    id: 'p-lap-5',
    title: 'CoolerCore Quad Fan Laptop Cooling Pad',
    price: 1299,
    originalPrice: 2499,
    description: 'Whisper-quiet thermals. Powered by quad high-speed 120mm fans with adjustable dial speeds, metal mesh structure for fast convection, and aesthetic blue backlights.',
    category: 'laptops',
    rating: 4.4,
    ratingCount: 110,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    specs: { 'Fan Setup': '4x 120mm Silent Fans', 'USB Pass': 'Dual Ports Integration', 'Ergonomics': '5 Adjustable Angles', 'RPM Speed': '1500 RPM Max' },
    stock: 50
  },

  // SECTION: FASHION
  {
    id: 'p3',
    title: 'Premium Minimalist Leather Backpack',
    price: 2499,
    originalPrice: 3999,
    description: 'Handcrafted full-grain leather backpack tailored for daily utility. Features dedicated velvet-lined compartments for 16-inch laptops, secondary powerbank pockets, and hidden safety passport slots.',
    category: 'fashion',
    rating: 4.6,
    ratingCount: 78,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80',
    specs: { 'Material': 'Full-Grain Leather', 'Size': '42 x 30 x 12 cm', 'Capacity': '18 Liters', 'Color': 'Tan Brown' },
    stock: 12,
    featured: true
  },
  {
    id: 'p-fash-2',
    title: 'Vogue Craft Men Regular Casual Shirt',
    price: 899,
    originalPrice: 1499,
    description: 'Premium woven cotton casual shirt. Highly breathable fabric with elegant single pocket detailing and soft spread collar structure.',
    category: 'fashion',
    rating: 4.4,
    ratingCount: 120,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
    specs: { 'Material': '100% Cotton Royal', 'Fit': 'Regular Fit Modern', 'Pattern': 'Solid Casual', 'Care': 'Machine Wash Soft' },
    stock: 45
  },
  {
    id: 'p-fash-3',
    title: 'Avaa Elegant Women Cotton Ethnic Kurti',
    price: 1299,
    originalPrice: 2199,
    description: 'Breathable festive Ethnic Kurti. Handcrafted with beautiful block print details, perfect for cultural events and smart daily comfort wear.',
    category: 'fashion',
    rating: 4.6,
    ratingCount: 95,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    specs: { 'Fabric': 'Pure Cambric Cotton', 'Weave': 'Traditional Block Print', 'Sleeve': 'Three-Quarter', 'Occasion': 'Festive / Casual' },
    stock: 28
  },
  {
    id: 'p6',
    title: 'Overcoat Cashmere Blend Trench',
    price: 4999,
    originalPrice: 7999,
    description: 'The definitive silhouette for professional wardrobes. Created with sustainably sourced cashmere fleece blends, offering supreme thermal protection while maintaining sleek negative profile spacing.',
    category: 'fashion',
    rating: 4.8,
    ratingCount: 52,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80',
    specs: { 'Material': '80% Cashmere, 20% Wool', 'Cut': 'Slim Fit', 'Length': 'Below Knee', 'Origin': 'Italy' },
    stock: 8,
    featured: true
  },
  {
    id: 'p-fash-5',
    title: 'UrbanFit Distressed Denim Jacket',
    price: 2199,
    originalPrice: 3499,
    description: 'Timeless layered styling. Heavily distressed authentic washed blue denim jacket with sturdy standard metal buttons and dual chest pockets.',
    category: 'fashion',
    rating: 4.5,
    ratingCount: 65,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&auto=format&fit=crop&q=80',
    specs: { 'Material': 'Heavyweight Cotton Denim', 'Color': 'Light Indigo Wash', 'Pockets': '2 Chest + 2 Hand Warmer Panels', 'Fit': 'Standard Relaxed' },
    stock: 18
  },

  // SECTION: FOOTWEAR
  {
    id: 'p-foot-1',
    title: 'Apex Run Pro Cushion Running Shoes',
    price: 2499,
    originalPrice: 3999,
    description: 'Superb responsive athletic trainer. Breathable custom knit upper structure, high impact absorption midsole support, and skid-proof carbon-rubber soles.',
    category: 'footwear',
    rating: 4.6,
    ratingCount: 142,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    specs: { 'Category': 'Performance Running', 'Midsole': 'Apex Cushion Foam', 'Weight': '260g (UK-8)', 'Arch Support': 'Neutral Pronation' },
    stock: 20,
    featured: true
  },
  {
    id: 'p-foot-2',
    title: 'Vogue Walk Urban Casual Sneakers',
    price: 1899,
    originalPrice: 2999,
    description: 'Premium vulcanized street-style sneakers. Soft padded memory-foam insoles coupled with high contrast classic stitch lines.',
    category: 'footwear',
    rating: 4.5,
    ratingCount: 110,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
    specs: { 'Material': 'Vegan Suede & Canvas', 'Sole': 'Non-slip Rubber Sole', 'Insole': 'Ortholite Memory Foam', 'Colours': 'Slate Gray / Cream White' },
    stock: 32
  },
  {
    id: 'p-foot-3',
    title: 'Royal Craft Men Premium Leather Formal Shoes',
    price: 2999,
    originalPrice: 4999,
    description: 'Exquisite derby formal shoes. Full-grain genuine leather upper, hand-burnished polish, and sleek cushioned outsoles for modern executive wear.',
    category: 'footwear',
    rating: 4.7,
    ratingCount: 75,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80',
    specs: { 'Style': 'Derby Brogue Cap-toe', 'Leather': 'Genuine Italian Calfskin', 'Insole': 'Ergonomic Leather Padded', 'Heel Height': '1.2 inches' },
    stock: 15
  },
  {
    id: 'p-foot-4',
    title: 'Avaa Comfort Block Heel Women Sandals',
    price: 1299,
    originalPrice: 1999,
    description: 'Elegant block heel sandals featuring high-grade elastic backstraps and textured slip-resistant front grips. Complements casual dresses and formal wear.',
    category: 'footwear',
    rating: 4.4,
    ratingCount: 48,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1603487390590-41ded7d2ba25?w=600&auto=format&fit=crop&q=80',
    specs: { 'Heel Style': '2.2" Block Heel', 'Upper': 'Premium Faux Leather Suede', 'Closure': 'Ankle Strap Snap', 'Footbed': 'Dual-density Cushioning' },
    stock: 22
  },
  {
    id: 'p-foot-5',
    title: 'Apex Comfort Slide Sports Slippers',
    price: 799,
    originalPrice: 1299,
    description: 'Standard poolside slides. Ultra lightweight single-injection EVA footbed with ergonomic curve matching to foot contours.',
    category: 'footwear',
    rating: 4.3,
    ratingCount: 130,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&auto=format&fit=crop&q=80',
    specs: { 'Material': '100% Hydrophobic Space EVA', 'Tread': 'Anti-Skid Hex Patterns', 'Weight': '98g (Ultra-Light)', 'Strap': 'Flexible Comfort Lining' },
    stock: 60
  },

  // SECTION: BEAUTY
  {
    id: 'p-beau-1',
    title: 'PureSense Salicylic Acid Face Wash',
    price: 349,
    originalPrice: 499,
    description: 'Re-invigorate facial pores. Infused with 2% active salicylic acid + green tea leaf extracts to safely prevent irritation and cleanse impurities gently.',
    category: 'beauty',
    rating: 4.5,
    ratingCount: 195,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
    specs: { 'Active Agent': '2% Salicylic Acid', 'Skin Type': 'Oily / Acne-Prone', 'Fragrance': 'Naturally Unscented', 'Volume': '150 ml' },
    stock: 45,
    featured: true
  },
  {
    id: 'p-beau-2',
    title: 'NexaBlock Matte finish SPF50 PA+++ Sunscreen',
    price: 499,
    originalPrice: 699,
    description: 'Standard high protection sunscreen. Zero white cast, matte texture, and standard sweat resistance. Defends fully against UVA/UVB.',
    category: 'beauty',
    rating: 4.6,
    ratingCount: 165,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80',
    specs: { 'SPF Index': 'SPF 50 PA+++', 'Protection': 'UVA & UVB Blocks', 'Finish': 'Matte Dry-touch Oil-free', 'Volume': '50g' },
    stock: 40
  },
  {
    id: 'p-beau-3',
    title: 'AuraGlow Intense Smooth Hair Serum',
    price: 399,
    originalPrice: 599,
    description: 'Nourish split ends and tame frizz. Enriched with cold-pressed Moroccan Argan Oil and Vitamin E to elevate hair silkiness and gloss.',
    category: 'beauty',
    rating: 4.4,
    ratingCount: 88,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80',
    specs: { 'Core Extract': 'Moroccan Argan Oil', 'Benefit': 'Anti-Frizz & Silk Satin Gloss', 'Protection': 'Thermal Heat Lock (Up to 230C)', 'Volume': '100 ml' },
    stock: 50
  },
  {
    id: 'p-beau-4',
    title: 'Vogue Lips Matte Liquid Lipstick Duo',
    price: 699,
    originalPrice: 999,
    description: 'Smudge-proof all-day lip color. Velvet texture, hyper-pigmented matte finish, and waterproof hydration holding up to 12 hours.',
    category: 'beauty',
    rating: 4.7,
    ratingCount: 104,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80',
    specs: { 'Finish': 'Velvet Weightless Matte', 'Longevity': '12-Hour Smudge-proof', 'Shades Included': 'Nude Crimson + Rust Rose', 'Formula': '100% Vegan & Cruelty-free' },
    stock: 35
  },
  {
    id: 'p7',
    title: 'HydraSkin Ceramide Deep Moisturizer',
    price: 449,
    originalPrice: 599,
    description: 'Barrier healing moisturizer. Contains 3 essential ceramides + hyaluronic acid to lock moisture for 24 hours of deep skin wellness.',
    category: 'beauty',
    rating: 4.8,
    ratingCount: 122,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
    specs: { 'Ceramides': 'NP, AP, EOP Core Complex', 'Hydrator': 'Multi-weight Hyaluronic Acid', 'Skin Type': 'Dry / Sensitive Skins', 'Volume': '80g' },
    stock: 30
  },

  // SECTION: GROCERY
  {
    id: 'p-groc-1',
    title: 'NexaBite Premium Long Grain Basmati Rice (5kg)',
    price: 649,
    originalPrice: 799,
    description: 'Delectable aromatic basmati grains. Aged matching authentic standard of 24 months, ideal for rich biryanis and daily luxury meals.',
    category: 'grocery',
    rating: 4.7,
    ratingCount: 160,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    specs: { 'Grain Size': '8.2 mm Average', 'Ageing': '24 Months Naturally', 'Aroma': 'High Natural Basmati', 'Net Weight': '5 kg' },
    stock: 50,
    featured: true
  },
  {
    id: 'p-groc-2',
    title: 'PureBlend Cold Pressed Mustard Oil (2L)',
    price: 399,
    originalPrice: 499,
    description: 'Sustainably sourced and extracted. Traditional cold-compress extraction retaining absolute nutritional minerals, sharp pungency, and natural fats.',
    category: 'grocery',
    rating: 4.6,
    ratingCount: 112,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    specs: { 'Extraction': 'Cold-Pressed Wood Pressed', 'Source': '100% Indian Mustard Seeds', 'Packaging': 'Bio-friendly PET Bottle', 'Volume': '2 Liters' },
    stock: 35
  },
  {
    id: 'p-groc-3',
    title: 'NexaBite Whole Wheat Sharbati Atta (10kg)',
    price: 489,
    originalPrice: 549,
    description: '100% MP Sharbati wheat grains. Stone-ground flour ensuring the softest rotis and preservation of essential dietary fibers.',
    category: 'grocery',
    rating: 4.5,
    ratingCount: 135,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    specs: { 'Wheat origin': 'Sehore Sharbati, MP', 'Mill Process': 'Chakki Stone Ground', 'Fibers': '11.8g per 100g Dietary Fiber', 'Net weight': '10 kg' },
    stock: 40
  },
  {
    id: 'p-groc-4',
    title: 'AuraTea Premium Assam Kadak Chai (1kg)',
    price: 329,
    originalPrice: 429,
    description: 'Carefully curated black tea blend from the finest gardens of Assam. Offers robust malt strength and rich standard sunrise color.',
    category: 'grocery',
    rating: 4.4,
    ratingCount: 95,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
    specs: { 'Tea Grade': 'BP & CTC Blends', 'Garden origin': 'Upper Assam Gardens', 'Infusion Time': '3-4 Minutes', 'Net Weight': '1 kg' },
    stock: 65
  },
  {
    id: 'p-groc-5',
    title: 'NutraBite Premium Mixed Dry Fruits (500g)',
    price: 699,
    originalPrice: 899,
    description: 'Premium energy booster. Balanced proportions of whole California Almonds, premium Cashews, Afghan Raisins, and fresh Greek Walnuts.',
    category: 'grocery',
    rating: 4.8,
    ratingCount: 75,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1595855759920-86582396756a?w=600&auto=format&fit=crop&q=80',
    specs: { 'Inclusions': 'Almonds, Cashews, Raisins, Walnuts', 'Quality': 'Grade A Jumbo Jumbo', 'Raw/Roasted': 'Plain Raw Natural', 'Net Weight': '500g' },
    stock: 25
  },

  // SECTION: HOME & KITCHEN
  {
    id: 'p-hk-1',
    title: 'NexaChef 750W Heavy Duty Mixer Grinder',
    price: 3499,
    originalPrice: 4999,
    description: 'Uncompromising blending speed. Powered by 750W high-torque copper motor, coupled with 3 surgical grade stainless steel jars for intense blending.',
    category: 'home-kitchen',
    rating: 4.5,
    ratingCount: 124,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&auto=format&fit=crop&q=80',
    specs: { 'Motor power': '750 Watts Pure Copper', 'Jars Included': '1.5L Wet, 1.0L Dry, 0.4L Chutney', 'Speed scale': '3 speed control with pulse', 'Warranty Details': '5 Years on Motor' },
    stock: 20,
    featured: true
  },
  {
    id: 'p-hk-2',
    title: 'KitchenPro Hard Anodized Non-stick Cookware Set (3pc)',
    price: 2199,
    originalPrice: 3299,
    description: 'Induction ready kitchen standard. Features deep kadhai with glass lid, flat fry pan, and solid dosa tawa with triple layer scratch guard.',
    category: 'home-kitchen',
    rating: 4.4,
    ratingCount: 88,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
    specs: { 'Base Type': 'Induction & Gas compatible', 'Coating': 'PFOA-free Triple Nonsticks', 'Items': 'Frypan, Kadhai, Tawa Panels', 'Color': 'Matte Charcoal Black' },
    stock: 15
  },
  {
    id: 'p-hk-3',
    title: 'CozyNest Pure Cotton Double Bedsheet Set',
    price: 1199,
    originalPrice: 1899,
    description: 'Indulge in cozy premium slumber. 100% breath holding cotton with high 300 thread count, featuring modern geometric panel prints and two pillow covers.',
    category: 'home-kitchen',
    rating: 4.6,
    ratingCount: 145,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    specs: { 'Material': '100% Long-staple Satin Cotton', 'Thread Count': '300 TC Premium Line', 'Dimensions': 'Bedsheet: 274 x 274 cm', 'Design': 'Sleek Geo Chevron Stripes' },
    stock: 40
  },
  {
    id: 'p-hk-4',
    title: 'SmartLock Airtight Kitchen Storage Containers (Set of 6)',
    price: 799,
    originalPrice: 1299,
    description: 'Save space and retain freshness. Beautiful glass-like BPA free acrylic containers with locking handles and custom labels for spices/cereals.',
    category: 'home-kitchen',
    rating: 4.5,
    ratingCount: 195,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=600&auto=format&fit=crop&q=80',
    specs: { 'Material': 'Food Grade BPA-free Acrylic', 'Seal Mechanism': 'One-Click Silicone Gaskets', 'Volume': '2x 1.2L + 2x 0.8L + 2x 0.5L', 'Transparency': 'High Clarity Clear View' },
    stock: 32
  },
  {
    id: 'p-hk-5',
    title: 'NexaHot Stainless Steel 1.8L Electric Kettle',
    price: 899,
    originalPrice: 1499,
    description: 'Boil water inside 120 seconds. Built with food-grade 304 double layer stainless steel, automatic thermostat shut-off, and cool touch handles.',
    category: 'home-kitchen',
    rating: 4.3,
    ratingCount: 220,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&auto=format&fit=crop&q=80',
    specs: { 'Boiling Capacity': '1.8 Liters', 'Power Index': '1500 Watts High Heat', 'Casing Material': '304 Stainless Steel Inner Shell', 'Safety Features': 'Dry Boiling Auto cutoff' },
    stock: 45
  },

  // SECTION: FURNITURE
  {
    id: 'p-furn-1',
    title: 'SpineCare Ergonomic High Back Office Chair',
    price: 6499,
    originalPrice: 9999,
    description: 'Professional posture solution. Fully adjustable high density nylon lumbar mesh support, 3D arms adjusters, and pneumatic gas lift holding up to 130kg.',
    category: 'furniture',
    rating: 4.7,
    ratingCount: 105,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=600&auto=format&fit=crop&q=80',
    specs: { 'Ergonomic Support': 'Adjustable Lumbar + Seat Tilt', 'Mesh Material': 'Dual Layer Breathable Nylon Mesh', 'Gas Lift Standard': 'Class 4 Heavy Duty', 'Wheel Casters': 'Anti-Scratch Polyurethane Casters' },
    stock: 15,
    featured: true
  },
  {
    id: 'p-furn-2',
    title: 'EcoWood Compact Study & Work Table',
    price: 3999,
    originalPrice: 5999,
    description: 'Standard desktop office solution. Engineered premium teak solidwood composite top, heavy duty matte black structural iron legs, and dual wire management grommets.',
    category: 'furniture',
    rating: 4.6,
    ratingCount: 88,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&auto=format&fit=crop&q=80',
    specs: { 'Wood Board': 'Pre-laminated Teak Board', 'Frame Material': 'Anti-rust Powder Coated Iron', 'Dimensions': '120 x 60 x 75 cm', 'Weight Capacity': '75 kg max' },
    stock: 18
  },
  {
    id: 'p-furn-3',
    title: 'ModularCraft 4-Tier Display Bookshelf',
    price: 2499,
    originalPrice: 3999,
    description: 'Amplify study interiors. Beautiful vintage wood finish shelves mapped with open wire ladders. Ideal for novels, awards, and potted plant displays.',
    category: 'furniture',
    rating: 4.5,
    ratingCount: 65,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&auto=format&fit=crop&q=80',
    specs: { 'Overall Shelves': '4 Open Tiers Columns', 'Frame Base': 'Cross-braced Metal Framing', 'Wood Type': 'E1 Environment Particleboard', 'Size': '95 x 30 x 140 cm' },
    stock: 24
  },
  {
    id: 'p-furn-4',
    title: 'CozyNest Fabric Tufted Single Sofa Chair',
    price: 7999,
    originalPrice: 11999,
    description: 'Lounge in supreme style. High density pocket sprung core cushions layered with premium velvet tufted texture and sturdy natural teak wood legs.',
    category: 'furniture',
    rating: 4.8,
    ratingCount: 42,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&auto=format&fit=crop&q=80',
    specs: { 'Seating Foam': 'High Resilience HR Foam (32 Density)', 'Fabric Velvet': 'Premium Breathable Velvet Fabric', 'Base support': 'Kiln-dried Hardwood structure', 'Colors': 'Emerald Green / Midnight Blue' },
    stock: 10
  },
  {
    id: 'p-furn-5',
    title: 'MinimalCraft Drawer Bedside Table',
    price: 1499,
    originalPrice: 2499,
    description: 'Aesthetic bedside storage. Features an open shelf layer, secondary deep smooth-glide drawer, and clean Scandinavian pine legs.',
    category: 'furniture',
    rating: 4.4,
    ratingCount: 110,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1532372320978-9b4d6a3a854c?w=600&auto=format&fit=crop&q=80',
    specs: { 'Style Design': 'Scandinavian Minimalism', 'Drawer channels': 'Metal Under-mount Runners Guide', 'Body composite': 'Medium Density Fiberboard (MDF)', 'Dimensions': '40 x 30 x 50 cm' },
    stock: 35
  },

  // SECTION: SPORTS
  {
    id: 'p5',
    title: 'EcoFit Anti-slip TPE 6mm Yoga Mat',
    price: 899,
    originalPrice: 1499,
    description: 'Perfect physical grip. Lightweight double layer non slip texture TPE composite, odorless, and comes with quick stretch carry straps.',
    category: 'sports',
    rating: 4.5,
    ratingCount: 185,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Material': 'Eco-TPE Poly-elastomer', 'Cushion': '6mm High-Recovery Cushion', 'Odour Lock': '100% Odorless Physical Shield', 'Length': '183 x 61 cm' },
    stock: 30,
    featured: true
  },
  {
    id: 'p-spor-2',
    title: 'Apex Iron Adjustable Hex Dumbbell Set (10kg)',
    price: 1499,
    originalPrice: 2499,
    description: 'Solid cast iron dumbbells. Heavy duty hexagonal heads preventing roll-aways during pushups, and knurled chrome handles for heavy grips.',
    category: 'sports',
    rating: 4.7,
    ratingCount: 140,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    specs: { 'Set Includes': '2x 5kg Hex Dumbbells', 'Body Core': 'Industrial Solid Cast Iron', 'Strap Coating': 'Heavy Duty Protective Rubber Shell', 'Grip': 'Knurled Ergonomic Chrome' },
    stock: 22
  },
  {
    id: 'p-spor-3',
    title: 'NexaStrike Premium Kashmiri Willow Cricket Bat',
    price: 2199,
    originalPrice: 3499,
    description: 'Grade A Kashmiri willow cricket bat. Handcrafted profile with massive sweet spot edges and webbed rubber grip for aggressive stroke play.',
    category: 'sports',
    rating: 4.6,
    ratingCount: 104,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&auto=format&fit=crop&q=80',
    specs: { 'Willow Grade': 'Grade A Selected Kashmiri Willow', 'Handle Type': 'Singapore Cane Treble Core Handle', 'Weight': '1180g (Regular/Senior)', 'Sweet Spot': 'Low-to-Mid Dynamic Sweetspot' },
    stock: 15
  },
  {
    id: 'p-spor-4',
    title: 'Apex Kick Pro Rubberized Football Size 5',
    price: 699,
    originalPrice: 999,
    description: 'Match grade football ready for turf drills. 32-panel machine stitched TPU laminate outer skin with durable butyl bladder.',
    category: 'sports',
    rating: 4.4,
    ratingCount: 194,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&auto=format&fit=crop&q=80',
    specs: { 'Size Standard': 'Official Match Size 5', 'Outer composite': 'Machine Stitched Synthetic PU Skin', 'Bladder': 'Durable Butyl Bladder Hold', 'Water Resistance': '100% Hydrophobic Seams' },
    stock: 45
  },
  {
    id: 'p-spor-5',
    title: 'AuraFit Leather Padded Gym Weightlifting Gloves',
    price: 499,
    originalPrice: 799,
    description: 'Skinsafe workout palms. Genuine leather outer body, heavy silicone textured padding on pressure spots, and integrated adjustable wrist wraps support.',
    category: 'sports',
    rating: 4.5,
    ratingCount: 112,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    specs: { 'Palm material': 'Genuine Calfskin Leather', 'Padding': '4mm Shock absorption Gel Padding', 'Wrist Wrap': '18" Elastic Wrist Wrap Strap', 'Washable': 'Cold Handwash safe' },
    stock: 55
  },

  // SECTION: TOYS
  {
    id: 'p-toy-1',
    title: 'NexaBlocks Creative Building Blocks Set (200+ pcs)',
    price: 1199,
    originalPrice: 1899,
    description: 'Ignite infant cognitive abilities. Sturdily interlocking BPA free ABS builders with geometric guides. Comes with reusable sorting bucket.',
    category: 'toys',
    rating: 4.6,
    ratingCount: 110,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1568016147631-c00624d7328d?w=600&auto=format&fit=crop&q=80',
    specs: { 'Piece count': '208 ABS block units', 'Material': '100% Non-toxic ABS Plastic', 'Age Group': 'Ages 3 and above', 'Compliance': 'CE Safety Standard Certified' },
    stock: 35,
    featured: true
  },
  {
    id: 'p-toy-2',
    title: 'TurboSpeed Off-Road RC Drift Car',
    price: 1499,
    originalPrice: 2499,
    description: 'Intense speed offroad buggy. 1:18 chassis with deep suspension links, long-distance 2.4GHz gun controller, and high performance rechargeable battery.',
    category: 'toys',
    rating: 4.5,
    ratingCount: 92,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Radio Standard': '2.4GHz Gun Control (80m range)', 'High Speed': '15 km/h Max speed', 'Battery Type': '3.7V Li-ion (25 Min runtime)', 'Terrain Use': 'Sand, Dirt, Grass, Rocks' },
    stock: 19
  },
  {
    id: 'p-toy-3',
    title: 'SmartIQ Brain Teaser 3D Wooden Puzzle',
    price: 599,
    originalPrice: 999,
    description: 'Engaging geometry puzzle. Crafted with smooth-burnished pine wood blocks, elevating spatial memory, patience, and visual coordinates.',
    category: 'toys',
    rating: 4.4,
    ratingCount: 54,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop&q=80',
    specs: { 'Material': 'Handcrafted Natural Pinewood', 'Puzzle types': 'Soma cube + T-pattern + Tangrams', 'Difficulty level': 'Moderate-to-Expert', 'Coating': 'Non-toxic Clear Varnish' },
    stock: 40
  },
  {
    id: 'p-toy-4',
    title: 'CozyPlush Large Fluffy Teddy Bear',
    price: 699,
    originalPrice: 1199,
    description: 'The absolute standard nursery buddy. Stuffed with ultra-soft hypoallergenic PP cotton fleece, secure lock pearl eyes, and cute bow detailing.',
    category: 'toys',
    rating: 4.7,
    ratingCount: 125,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1559251606-c623743a6d76?w=600&auto=format&fit=crop&q=80',
    specs: { 'Overall Height': '60 cm Sitting Height', 'Fabric Material': 'Super Soft Microcore Plush', 'Stuffing': 'Premium Hypoallergenic PP Cotton', 'Safety Checks': 'EN71 Safety standards certified' },
    stock: 32
  },
  {
    id: 'p-toy-5',
    title: 'ColorCraft 72-Piece Premium Kids Art & Craft Kit',
    price: 899,
    originalPrice: 1499,
    description: 'Complete art suitcase. Double-decker carrying box including watercolors, crayons, sketch pens, physical scissors, safe glue blocks, and drawing cards.',
    category: 'toys',
    rating: 4.5,
    ratingCount: 78,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Items Inside': '24 Crayons, 24 Sketches, 12 Paints', 'Storage Box': 'Foldable Aluminum-Clad Suitcase', 'Toxic Rating': 'AP Certified Non-toxic Safety', 'Weight': '1.1 kg' },
    stock: 24
  },

  // SECTION: BOOKS
  {
    id: 'p-book-1',
    title: 'Shadows of Nexa: Epic Fiction Mystery Novel',
    price: 399,
    originalPrice: 599,
    description: 'Delve into the bestselling sci-fi thriller. Written by renowned visual worldbuilder Arthur Pendelton, charting cybernetic espionage networks standard.',
    category: 'books',
    rating: 4.6,
    ratingCount: 142,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Author Name': 'Arthur Pendelton', 'Format Type': 'Paperback Softcover Edition', 'Page Count': '412 Pages', 'Publishing House': 'Nexa Print Media' },
    stock: 45,
    featured: true
  },
  {
    id: 'p-book-2',
    title: 'AuraMind: Guide to Mind Clarity Self-Help',
    price: 299,
    originalPrice: 499,
    description: 'Bestselling self help manual detailing daily cognitive tricks to streamline work streams, clear focus noises, and organize dynamic thinking patterns.',
    category: 'books',
    rating: 4.8,
    ratingCount: 205,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Author Name': 'Dr. Julian Vane', 'Category': 'Mindfulness & Habits', 'Language': 'English', 'Format': 'Hardcover Premium' },
    stock: 50
  },
  {
    id: 'p-book-3',
    title: 'NexaPrep Comprehensive Quantitative Aptitude Guide',
    price: 549,
    originalPrice: 799,
    description: 'Standard blueprint for elite competitive examinations. Focuses on shortcut arithmetic rules, mock datasets templates, and previous year solutions keys.',
    category: 'books',
    rating: 4.5,
    ratingCount: 110,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
    specs: { 'Exam Type': 'GMAT, UPSC, Bank Examinations', 'Solutions Core': '1500+ Solved Math Problems', 'Edition': '2026 Latest Standard Edition', 'Publishers': 'AuraTech Educationals' },
    stock: 65
  },
  {
    id: 'p-book-4',
    title: 'Synergy Engine: High Output Scalability Business Book',
    price: 449,
    originalPrice: 699,
    description: 'The corporate playbook of modern founders. Insights into high growth organizational culture, product division templates, and cashflow holding loops.',
    category: 'books',
    rating: 4.7,
    ratingCount: 89,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Author': 'David V. Masters', 'Audience': 'Founders & VC Managers', 'ISBN Code': '978-3-16-148410-0', 'Duration': 'Express 6-hour Read' },
    stock: 24
  },
  {
    id: 'p-book-5',
    title: 'JoyLand Illustrated Bedtime Children Story Book',
    price: 199,
    originalPrice: 349,
    description: 'Charming graphic fairy tale collection. Features high contrast aesthetic visual art panels paired with bedtime moral coordinate summaries.',
    category: 'books',
    rating: 4.6,
    ratingCount: 76,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
    specs: { 'Age standard': 'Ages 3 to 8 Years', 'Binding Format': 'Thick Glossy board Book', 'Illustration Type': 'Premium Hand-painted Watercolors', 'Pages Total': '48 Premium Pages' },
    stock: 35
  },

  // SECTION: AUTOMOTIVE
  {
    id: 'p-auto-1',
    title: 'NexaDrive High Power Handheld Car Vacuum Cleaner',
    price: 1899,
    originalPrice: 2999,
    description: 'Intense cyclone dust buster. 12V direct dashboard power outlet adapter plug, powerful 6000PA motor suction, and washable metal HEPA filter grid.',
    category: 'automotive',
    rating: 4.5,
    ratingCount: 104,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=600&auto=format&fit=crop&q=80',
    specs: { 'Suction Rating': '6000 PA Cyclone Suction', 'Connector Cord': '4.5m 12V Car Cigarette Lighter', 'Filter Unit': 'Double Filter Stainless Steel HEPA', 'Weight': '850 grams' },
    stock: 22,
    featured: true
  },
  {
    id: 'p-auto-2',
    title: 'ApexShield ISI Certified Full Face Bike Helmet',
    price: 1499,
    originalPrice: 2499,
    description: 'Superior physical defense. ISI marked high density outer polycarbonate, rapid-click buckle wrap, air flowing duct vents, and anti scratch front shield.',
    category: 'automotive',
    rating: 4.7,
    ratingCount: 145,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?w=600&auto=format&fit=crop&q=80',
    specs: { 'Safety Standard': 'ISI Certified (IS:4151)', 'Shell Material': 'Impact Resistant Polycarbonate', 'Visor': 'Dual Visor with Anti-scratch shield', 'Inner Core': 'EPS Density Foam Liner' },
    stock: 18
  },
  {
    id: 'p-auto-3',
    title: 'DriveSecure Dashboard Air Vent Car Mobile Holder',
    price: 399,
    originalPrice: 799,
    description: 'Sturdy physical lock. Mechanical auto grip arms holding any smartphone tightly on air flow slats. 360 rotation adjustment dials.',
    category: 'automotive',
    rating: 4.3,
    ratingCount: 220,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
    specs: { 'Mounting base': 'Auto-Locking Air Vent Clip', 'Compatibilities': 'All Devices 4.5" to 7.0"', 'Materials': 'Premium ABS & Anti-slip Silicone', 'Rotation Angle': '360 degree ball joint' },
    stock: 65
  },
  {
    id: 'p-auto-4',
    title: 'ShineCraft Microfiber Car Cleaning Cloth (4-Pack)',
    price: 349,
    originalPrice: 599,
    description: 'Lint-free express shine fabrics. Thick 800GSM microfibers absorbing water matching 10x target weight, preventing any scratching on high gloss coatings.',
    category: 'automotive',
    rating: 4.6,
    ratingCount: 310,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&auto=format&fit=crop&q=80',
    specs: { 'Cloth Thicken': '800 GSM Heavyweight Cloth', 'Fabric blend': '80% Polyester, 20% Polyamide', 'Quantity Set': '4 Microfiber Cloth Pack', 'Colors': 'High Contrast Yellow/Grey' },
    stock: 120
  },
  {
    id: 'p-auto-5',
    title: 'DrivePower Digital Auto Tyre Inflator Pump',
    price: 2499,
    originalPrice: 3999,
    description: 'Save vehicle down times. Plug directly into 12V outputs, specify desired tyre pressure, and watch the auto shut-off lock precision values perfectly.',
    category: 'automotive',
    rating: 4.6,
    ratingCount: 88,
    sellerId: 'v4',
    sellerName: 'Apex Athletics',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=600&auto=format&fit=crop&q=80',
    specs: { 'Power Input': '12V DC Car Adapter', 'Max Air Pressure': '150 PSI Precision Gauge', 'Inflating speed': '35 L/Min heavy air flow', 'Display Monitor': 'Backlit LCD Digital Screen' },
    stock: 15
  },

  // SECTION: HEALTH
  {
    id: 'p-heal-1',
    title: 'CareTouch Fast Response Digital Body Thermometer',
    price: 249,
    originalPrice: 499,
    description: 'Clinical precision thermal sensor. Medical grade digital thermometer with auto warning buzzer tones for fever and last state record cache logs.',
    category: 'health',
    rating: 4.4,
    ratingCount: 165,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    specs: { 'Sensor Tech': 'Rapid-sensing thermistor', 'Accuracy': '+-0.1 Degree Celcius', 'Battery Power': 'LR41 Standard button cell', 'Display': 'High Contrast LCD screen' },
    stock: 95,
    featured: true
  },
  {
    id: 'p-heal-2',
    title: 'CareTouch Digital Upper Arm Blood Pressure Monitor',
    price: 1899,
    originalPrice: 2999,
    description: 'Reliability vascular readings at home. Advanced digital oscillometric upper arm cuff, smart posture warnings, and split 90 memory panels.',
    category: 'health',
    rating: 4.6,
    ratingCount: 110,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    specs: { 'Method type': 'Oscillometric Upper Arm Cuff', 'Cuff size range': '22 cm to 42 cm circumference', 'Storage Cache': 'Dual user 90 memory slots each', 'Power options': '4x AA Batteries / USB Type-C' },
    stock: 24
  },
  {
    id: 'p-heal-3',
    title: 'AuraFit Leakproof Blender Protein Shaker Bottle',
    price: 349,
    originalPrice: 599,
    description: 'Lumps free recovery beverages. Sturdy surgical grade stainless steel whisk ball, leakproof screw lids, and dedicated protein supplement storage cups.',
    category: 'health',
    rating: 4.5,
    ratingCount: 145,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    specs: { 'Volume size': '700 ml fluid holding', 'Mixer tech': '316 Surgical Metal Whisk Ball', 'Composite': 'BPA-free Tritan Plastic', 'Leak Proof': 'Thread lock security seal' },
    stock: 42
  },
  {
    id: 'p-heal-4',
    title: 'CareTouch Emergency Multi-item First Aid Kit',
    price: 599,
    originalPrice: 999,
    description: 'Definitive home safety bundle. Fabric zipper pouch holding sterile adhesive dressings, elastic bandage rolls, antiseptic wipes, scissors, and burns gels.',
    category: 'health',
    rating: 4.7,
    ratingCount: 78,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=600&auto=format&fit=crop&q=80',
    specs: { 'Case material': 'EVA Hard Shell water repellent', 'Total items': '50 Essential Medical pieces', 'Standards': 'FDA & ISO Standards compliant', 'Expiry Period': '3 Year Shelf life' },
    stock: 35
  },
  {
    id: 'p-heal-5',
    title: 'CarePulse Heart Rate tracking Fitness Band',
    price: 1499,
    originalPrice: 2499,
    description: 'Monitor physical indicators hourly. Vibrant rectangular color screen verifying blood oxygen, tracking 15 sport modes, and providing smart sleep logs.',
    category: 'health',
    rating: 4.3,
    ratingCount: 112,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop&q=80',
    specs: { 'Activity tracking': 'Steps, distance, calories, sleep', 'Vascular checks': 'SpO2 oxygen + Continuous PPG', 'Water Proof': 'IP68 Swimwear safe', 'Battery standby': '10 Days continuous use' },
    stock: 28
  },

  // SECTION: WATCHES
  {
    id: 'p2',
    title: 'Apex Fit Smartwatch v3',
    price: 4499,
    originalPrice: 5999,
    description: 'All-weather smart activity companion that tracks core metrics, cellular messages, coordinates, and sleep cycles. Built with aerospace aluminum casing and ultra-bright AMOLED circular display.',
    category: 'watches',
    rating: 4.7,
    ratingCount: 95,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    specs: { 'Display': '1.43" AMOLED', 'Battery': '14 Days', 'Waterproof': '5ATM IP68', 'Casing': 'Aluminum' },
    stock: 22,
    featured: true
  },
  {
    id: 'p-wat-2',
    title: 'Vogue Chrono Leather Strap Analog Watch',
    price: 2199,
    originalPrice: 3499,
    description: 'Timeless visual elegance. Genuine tanned brown leather straps, high accuracy Japanese quartz mechanical oscillators, and 3-dial chronograph arrays.',
    category: 'watches',
    rating: 4.5,
    ratingCount: 78,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&auto=format&fit=crop&q=80',
    specs: { 'Strap size': '22mm Genuine Leather', 'Glass crystal': 'Mineral scratch resistant glass face', 'Water depth': '30m water resistance (3ATM)', 'Movement': 'Japanese Citizen Quartz' },
    stock: 15
  },
  {
    id: 'p-wat-3',
    title: 'Apex Tachometer Waterproof Sports Watch',
    price: 1899,
    originalPrice: 2999,
    description: 'Rugged dive-ready sports watch. Multi-function digital tachometer, glowing backlighting, impact absorption rubber outer bumpers, and split micro-chronograph.',
    category: 'watches',
    rating: 4.4,
    ratingCount: 62,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&auto=format&fit=crop&q=80',
    specs: { 'Dial Display': 'Dual Analog + Digital panels', 'Alarms support': 'Set up to 3 daily reminders', 'Chronograph': '1/1000th second dial index', 'Armor Base': 'Carbon reinforced resin shell' },
    stock: 24
  },
  {
    id: 'p-wat-4',
    title: 'Royal Gold Dial Luxury Metal Chronograph Watch',
    price: 8999,
    originalPrice: 12999,
    description: 'An undeniable status declaration. Styled with beautiful gold electro-plated steel straps, sapphire crystal glass faces, and dual lock foldover snaps.',
    category: 'watches',
    rating: 4.8,
    ratingCount: 38,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=600&auto=format&fit=crop&q=80',
    specs: { 'Steel Type': '315L Solid Stainless Steel', 'Coating': '24K Gold PVD Coating', 'Lens Face': 'Pure Scratchless Sapphire Glass', 'Bezel Ring': 'Fluted Luxury Bezel Ring' },
    stock: 8
  },
  {
    id: 'p-wat-5',
    title: 'JoyLand Colorful Digital Kids Watch',
    price: 499,
    originalPrice: 799,
    description: 'Nursery time management buddy. Soft skinsafe silicone bands with beautiful graphic cartoon themes, digital clock display, and soft light buttons.',
    category: 'watches',
    rating: 4.3,
    ratingCount: 110,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=600&auto=format&fit=crop&q=80',
    specs: { 'Strap comfort': '100% Phthalate free Soft Silicone', 'Clock setup': '24-Hour Digital + alarm buzzer', 'Fun Feature': 'Multi-colour LED glowing dial', 'Battery life': '2 Year replaceable cell' },
    stock: 35
  },

  // SECTION: JEWELRY
  {
    id: 'p-jew-1',
    title: 'AuraGlow 925 Sterling Silver Adjustable Ring',
    price: 1299,
    originalPrice: 1999,
    description: 'Crafted with premium precious materials. Solid 925 sterling silver bands presenting a stunning brilliant cut central simulated diamond.',
    category: 'jewelry',
    rating: 4.6,
    ratingCount: 95,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80',
    specs: { 'Precious Metal': '925 Sterling Silver Core', 'Plating': 'Rhodium Plating Anti tarnish', 'Gemstone': 'AAAAA Cubic Zirconia Brilliant Cut', 'Ring Size': 'Adjustable Universal Fitting' },
    stock: 15,
    featured: true
  },
  {
    id: 'p-jew-2',
    title: 'Royal Gold-Plated Unisex Minimalist Chain',
    price: 1499,
    originalPrice: 2499,
    description: 'Elegant accessorizing. Lightweight and beautiful 18K gold-plated brass chain with premium lobster clasps claw snap security.',
    category: 'jewelry',
    rating: 4.5,
    ratingCount: 78,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Coating Metal': '18k Real Yellow Gold Plating', 'Chain Pattern': 'Italian Curb Link design', 'Overall Length': '20 inches / 50 cm Size', 'Claw closure': 'Lobster clasp claw connector' },
    stock: 22
  },
  {
    id: 'p-jew-3',
    title: 'Avaa Elegant Pearl Drop Earrings Set (3 Pairs)',
    price: 699,
    originalPrice: 1199,
    description: 'Complement ethnic and modern office wear. Set of three distinct pairs styled with organic freshwater cultured pearls.',
    category: 'jewelry',
    rating: 4.7,
    ratingCount: 112,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
    specs: { 'Stone type': 'A-grade Freshwater Cultured Pearls', 'Earrings Base': 'Surgical Stainless Steel hypo-allergenic', 'Colors Included': 'Snow White, Peach Pink, Lavender', 'Pairings Set': '3 Pairs (Drop, Stud, Hoop designs)' },
    stock: 32
  },
  {
    id: 'p-jew-4',
    title: 'AuraGlow Adjustable Silver Charm Bracelet',
    price: 999,
    originalPrice: 1599,
    description: 'Delightful jewelry gift choice. Beautiful double looped silver cable chain matching with three custom travel and floral visual charms.',
    category: 'jewelry',
    rating: 4.4,
    ratingCount: 54,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&auto=format&fit=crop&q=80',
    specs: { 'Bracelet style': 'Sleek Link cable bracelet', 'Overall Length': '17 cm to 21 cm range', 'Charms Included': 'Eiffel tower + Daisy + Sapphire Heart', 'Metal Base': 'Electro-plated Sterling Silver finish' },
    stock: 40
  },
  {
    id: 'p-jew-5',
    title: 'Royal Solitaire Diamond Accent Pendant Necklace',
    price: 1899,
    originalPrice: 2899,
    description: 'Exquisite teardrop design. Shipped inside protective velvet giftboxes. Features single floating round cut simulated diamond accent.',
    category: 'jewelry',
    rating: 4.8,
    ratingCount: 65,
    sellerId: 'v2',
    sellerName: 'Vogue Essentials',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Chain material': 'Standard Brass with Rhodium gloss', 'Diamond size': '1.0 Carat equivalent Solitaire', 'Necklace Size': '45 cm with 5 cm loops expansion', 'Weight': '4.2 grams target weight' },
    stock: 15
  },

  // SECTION: BABY PRODUCTS
  {
    id: 'p-baby-1',
    title: 'SoftTouch Premium Ultra Absorb Baby Diapers (Set of 48)',
    price: 799,
    originalPrice: 1199,
    description: 'Ensure baby skin dryness throughout the night. Crafted with hyper-breathable cotton fibers, unique elastic waist leak guards, and wetness indication lines.',
    category: 'baby-products',
    rating: 4.6,
    ratingCount: 135,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&auto=format&fit=crop&q=80',
    specs: { 'Ideal for': 'Size M (6 kg to 11 kg infants)', 'Diaper Pack': '48 Premium Cotton Diapers Set', 'Skin Wellness': 'Zero chemical dyes, Aloe Vera Infused', 'Dry Retention': 'Up to 12 Hours Absorbency' },
    stock: 45,
    featured: true
  },
  {
    id: 'p-baby-2',
    title: 'SoftTouch Gentle Nourish Hypoallergenic Baby Lotion',
    price: 299,
    originalPrice: 499,
    description: 'Carefully curated moisturization skins. Formulated with cold-pressed sweet almond oils, natural shea butter, and pure water extracts.',
    category: 'baby-products',
    rating: 4.7,
    ratingCount: 110,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
    specs: { 'Formula Checks': 'Pediatrician certified, clinically tested', 'Key extracts': 'Organic Chamomile & Shea Butter', 'Toxic scale': 'Paraben-free, Sulphate-free', 'Volume size': '200 ml bottle' },
    stock: 32
  },
  {
    id: 'p-baby-3',
    title: 'SoftTouch Anti-Colic Wide Neck Baby Feeding Bottle',
    price: 399,
    originalPrice: 599,
    description: 'Skinsafe food-grade feeding bottle. Ultra soft breast-like silicone nipple, special double ventilation air valves preventing colic issues.',
    category: 'baby-products',
    rating: 4.5,
    ratingCount: 92,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    specs: { 'Bottle volume': '250 ml volume standard', 'Nipple size': 'Medium Flow (suitable for 3-6 months)', 'Material body': '100% BPA-free Polypropylene (PP)', 'Ventilation': 'Dual anti-colic ventilation air valve' },
    stock: 24
  },
  {
    id: 'p-baby-4',
    title: 'CozyNest Ultra Soft Flannel Printed Baby Blanket',
    price: 699,
    originalPrice: 999,
    description: 'Snuggle your toddler in supreme safety. Premium double-faced lightweight flannel fabrics with beautiful graphics.',
    category: 'baby-products',
    rating: 4.5,
    ratingCount: 54,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&auto=format&fit=crop&q=80',
    specs: { 'Fabric Type': '100% Micro-polar Flannel fleece', 'Design Theme': 'Cute Sleeping Sloth print', 'Dimensions': '100 cm x 140 cm size', 'Washable': 'Machine Washable on cold delicates' },
    stock: 40
  },
  {
    id: 'p-baby-5',
    title: 'JoyLand Montessori Sensory Rattles Baby Toy Set',
    price: 899,
    originalPrice: 1299,
    description: 'Safe teething handles. 6 sensory organic rattles and teething ring composite pieces satisfying infants motor learning guides.',
    category: 'baby-products',
    rating: 4.6,
    ratingCount: 78,
    sellerId: 'v3',
    sellerName: 'EcoVentures',
    image: 'https://images.unsplash.com/photo-1559251606-c623743a6d76?w=600&auto=format&fit=crop&q=80',
    specs: { 'Units total': '6 teething rattle objects set', 'Material safe': 'Food-grade Silicone + ABS composite', 'Age standard': 'Suitable for 0 to 18 months', 'Certifications': 'ASTM & CPC Safety Certified' },
    stock: 15
  },

  // SECTION: SMART HOME
  {
    id: 'p4',
    title: 'NexaGlow Smart Ambilight Bar',
    price: 2499,
    originalPrice: 3999,
    description: 'Breathe vibrant, synchronized color schemes into your desktop setup. Features intelligent microphone-level spatial audio sync, dedicated desktop app controls, and integration with popular smart servers.',
    category: 'smart-home',
    rating: 4.9,
    ratingCount: 242,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Interface': 'USB Type-C', 'Colors': '16.8 Million RGB', 'Length': '45 cm', 'App Integration': 'Siri/Google/Alexa' },
    stock: 65,
    featured: true
  },
  {
    id: 'p-sh-2',
    title: 'NexaGlow Smart LED Bulb Pack of 3',
    price: 899,
    originalPrice: 1499,
    description: 'Control your ambiance with simple app touches. Features integration with Alexa and Google smart servers, 16 million colors palettes.',
    category: 'smart-home',
    rating: 4.6,
    ratingCount: 120,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Voltage': '9W Smart Bulb', 'Colors': '16 Million RGB', 'Integration': 'Alexa & Google Assistant' },
    stock: 40
  },
  {
    id: 'p-sh-3',
    title: 'NexaGlow Secure Digital Door Lock',
    price: 6499,
    originalPrice: 8999,
    description: 'Keep your sanctuary safe. Standard smart biometric finger scanners matching high grade AES-128 database lock encryptions.',
    category: 'smart-home',
    rating: 4.8,
    ratingCount: 45,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    specs: { 'Unlock Methods': 'Fingerprint, PIN Key, Physical Override Card', 'Data Security': 'Built-in Offline security chip' },
    stock: 15
  },
  {
    id: 'p-sh-4',
    title: 'AuraTech Smart Plug Mini Set-of-2',
    price: 999,
    originalPrice: 1499,
    description: 'Automate any dumb electrical device. Power timers, real-time electricity tracking logs, and direct Wi-Fi control integrations.',
    category: 'smart-home',
    rating: 4.5,
    ratingCount: 88,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Max Load': '16A High Power load', 'Network Support': '2.4GHz WiFi Connection Only' },
    stock: 50
  },
  {
    id: 'p-sh-5',
    title: 'NexaGlow Breathe Smart Air Purifier',
    price: 8999,
    originalPrice: 11999,
    description: 'Cleanse raw indoor dust. True Hepa 13 particulate layers tracking AQI live metrics, reporting real-time clean air delivery rates.',
    category: 'smart-home',
    rating: 4.7,
    ratingCount: 35,
    sellerId: 'v1',
    sellerName: 'AuraTech Officials',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    specs: { 'Filter Standard': 'H13 True HEPA Active Carbon layers', 'CADR Speed': '250 m3/h filtration delivery' },
    stock: 12
  }
];

export const defaultOrders: Order[] = [
  {
    id: 'ORD-89302',
    date: '2026-05-18T14:32:00Z',
    items: [
      {
        productId: 'p1',
        title: 'SoundAura Wireless ANC Headphones',
        quantity: 1,
        price: 4999,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=150&auto=format&fit=crop&q=80',
        sellerId: 'v1'
      },
      {
        productId: 'p4',
        title: 'NexaGlow Smart Ambilight Bar',
        quantity: 1,
        price: 2499,
        image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=150&auto=format&fit=crop&q=80',
        sellerId: 'v1'
      }
    ],
    total: 7498,
    status: 'delivered',
    shippingAddress: {
      fullName: 'Prem Kumar',
      street: '124 Innovation Boulevard, Tech District',
      city: 'Bangalore',
      state: 'Karnataka',
      zip: '560001'
    },
    trackingNumber: 'TRK-9830210A8',
    paymentMethod: 'Credit Card (Visa)'
  },
  {
    id: 'ORD-76121',
    date: '2026-05-23T09:15:00Z',
    items: [
      {
        productId: 'p3',
        title: 'Premium Minimalist Leather Backpack',
        quantity: 1,
        price: 2499,
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=150&auto=format&fit=crop&q=80',
        sellerId: 'v2'
      }
    ],
    total: 2499,
    status: 'shipped',
    shippingAddress: {
      fullName: 'Prem Kumar',
      street: '124 Innovation Boulevard, Tech District',
      city: 'Bangalore',
      state: 'Karnataka',
      zip: '560001'
    },
    trackingNumber: 'TRK-2410841B9',
    paymentMethod: 'UPI'
  }
];

export const helpArticles: HelpArticle[] = [
  {
    id: 'h1',
    title: 'How do I start selling on ShopNexa?',
    category: 'Sellers & Vendors',
    content: 'Starting your seller journey on ShopNexa takes less than five minutes. Simply head to your Vendor Profile via the top bar or standard portal, complete your business identity validation, specify your payout bank or merchant details, and upload your products immediately. ShopNexa charges an average minor standard platform commission rate depending on categories, which is deducted direct-to-destination during active payouts.',
    views: 1245
  },
  {
    id: 'h2',
    title: 'Understanding Platform Commission Rates',
    category: 'Sellers & Vendors',
    content: 'ShopNexa implements a highly competitive tier-based commission model scaling between 8% to 12% depending fully on product categories. Electronics maintain a sleek 8% commission rate, Sports and Wellness stay at 10%, while Fashion sits matching at 12%. No hidden setup, monthly integration maintenance, or API usage fees apply.',
    views: 890
  },
  {
    id: 'h3',
    title: 'What is the standard Buyer Guarantee Policy?',
    category: 'Buyers & Orders',
    content: 'Your security is ShopNexas absolute standard. Every purchase benefits from 14-day full buyer protection. Funds are safely held in an internal escrow pool. After the product registers as delivered, the funds release securely to the vendor after 48 hours unless a dispute is active. Standard refunds are processed to your original routing route or payment path within 5-7 business days.',
    views: 2410
  },
  {
    id: 'h4',
    title: 'Track and manage your incoming deliveries',
    category: 'Buyers & Orders',
    content: 'Once a vendor validates your cargo or assigns tracking numbers, your User Dashboard will highlight active tracking codes with direct tracking links. You can also opt-in for express SMTP coordinates or SMS update notifications for hourly tracking changes.',
    views: 1845
  },
  {
    id: 'h5',
    title: 'Standardizing Payment Gateway Actions',
    category: 'Payments & Refunds',
    content: 'ShopNexa maintains direct premium interfaces with Stripe, Google Wallet, UPI, and major integrated network cards. All security measures utilize AES-256 standard database level layers matching high banking protocols. Your credentials never cross raw unencrypted logs.',
    views: 650
  }
];

export const mockReviewsByProductId: { [key: string]: any[] } = {
  'p1': [
    { id: 'r1', author: 'Vikram S.', rating: 5, date: '2026-05-12', comment: 'Spectacular sound signature. The passive seal is great, but starting hybrid ANC is where the magic happens. Highly recommend!', helpfulCount: 42 },
    { id: 'r2', author: 'Nisha R.', rating: 4, date: '2026-05-15', comment: 'Incredibly comfortable for 6-hour code streaks. Audio is crisp, slightly boosted bass profiles. Solid warranty periods.', helpfulCount: 15 }
  ],
  'p3': [
    { id: 'r3', author: 'Aravind K.', rating: 5, date: '2026-04-20', comment: 'Exquisite stitching and authentic full-grain leather scent. Compact yet fits my 16" notebook perfectly without bulging. Received lots of compliments.', helpfulCount: 28 }
  ]
};
